---
esphome:
  name: lr

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "192.168.1.134"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lr Fallback Hotspot"
    password: "H2xtXXQ4r2Up"

captive_portal:

one_wire:
  - platform: gpio
    pin: GPIO02

sensor:
  - platform: adc
    pin: GPIO17
    name: "Test brightness"
    update_interval: 60s
    filters:
      - multiply: 3.3
  - platform: dallas_temp
    name: "temperature"
    update_interval: 60s

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_log_user
  password: !secret mqtt_log_password
  log_topic: esphome
  birth_message:
    topic: esphome
    payload: "birth"
  shutdown_message:
    topic: esphome
    payload: "shutdown"
  will_message:
    topic: esphome
    payload: "died"
